aplicacao/
    __init__.py
    core/
        __init__.py
        event_treatment.py
        gathering.py
        GetValuesSensor.py
        main.py
        mtbottle.py
        mtwsgi.py
        proceeding.py
        publisher.py
        rest.py
        scheduler.py
    moduleOfRules/
        __init__.py
        ActionRules.py
        ConditionsRules.py
        CopyConditionsRules.py
        createConditions.py
        EngineRuleEdge.py
        MainTeste.py
        Parameters.py
        schedulerEdge.py
        
