# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actuators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuID', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='BaseParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ContextServers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('addressUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Gateways',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuID', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Persistances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectDate', models.DateTimeField()),
                ('value', models.FloatField()),
                ('contextServer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lupsEdgeServer.ContextServers')),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jsonRule', models.TextField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schType', models.CharField(choices=[('i', 'Interval'), ('d', 'Date'), ('c', 'Cron')], default='i', max_length=1)),
                ('status', models.BooleanField()),
                ('cron', models.TextField()),
                ('interval', models.TextField()),
                ('date', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuID', models.CharField(max_length=36)),
                ('model', models.CharField(max_length=30)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lupsEdgeServer.Gateways')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lupsEdgeServer.Manufacturers')),
            ],
        ),
        migrations.CreateModel(
            name='SensorsTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='sensors',
            name='sensorType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lupsEdgeServer.SensorsTypes'),
        ),
        migrations.AddField(
            model_name='schedules',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lupsEdgeServer.Sensors'),
        ),
        migrations.AddField(
            model_name='rules',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lupsEdgeServer.Sensors'),
        ),
        migrations.AddField(
            model_name='persistances',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lupsEdgeServer.Sensors'),
        ),
        migrations.AddField(
            model_name='gateways',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lupsEdgeServer.Manufacturers'),
        ),
        migrations.AddField(
            model_name='actuators',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lupsEdgeServer.Gateways'),
        ),
    ]
