# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lupsEdgeServer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actuators',
            new_name='Actuator',
        ),
        migrations.RenameModel(
            old_name='BaseParameters',
            new_name='BaseParameter',
        ),
        migrations.RenameModel(
            old_name='ContextServers',
            new_name='ContextServer',
        ),
        migrations.RenameModel(
            old_name='Gateways',
            new_name='Gateway',
        ),
        migrations.RenameModel(
            old_name='Manufacturers',
            new_name='Manufacturer',
        ),
        migrations.RenameModel(
            old_name='Persistances',
            new_name='Persistance',
        ),
        migrations.RenameModel(
            old_name='Rules',
            new_name='Rule',
        ),
        migrations.RenameModel(
            old_name='Schedules',
            new_name='Schedule',
        ),
        migrations.RenameModel(
            old_name='Sensors',
            new_name='Sensor',
        ),
        migrations.RenameModel(
            old_name='SensorsTypes',
            new_name='SensorType',
        ),
    ]
