# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-09 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actuator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuID', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='BaseParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ContextServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('addressUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuID', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Persistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectDate', models.DateTimeField()),
                ('value', models.FloatField()),
                ('contextServer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API_RestFul.ContextServer')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jsonRule', models.TextField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schType', models.CharField(choices=[('i', 'Interval'), ('d', 'Date'), ('c', 'Cron')], default='i', max_length=1)),
                ('status', models.BooleanField()),
                ('cron', models.TextField(blank=True)),
                ('interval', models.TextField(blank=True)),
                ('date', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuID', models.CharField(max_length=36)),
                ('model', models.CharField(max_length=30)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_RestFul.Gateway')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_RestFul.Manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensorType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_RestFul.SensorType'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_RestFul.Sensor'),
        ),
        migrations.AddField(
            model_name='rule',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_RestFul.Sensor'),
        ),
        migrations.AddField(
            model_name='persistance',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API_RestFul.Sensor'),
        ),
        migrations.AddField(
            model_name='gateway',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_RestFul.Manufacturer'),
        ),
        migrations.AddField(
            model_name='actuator',
            name='gateway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_RestFul.Gateway'),
        ),
    ]
