# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_RestFul', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuator',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API_RestFul.Manufacturer'),
        ),
        migrations.AddField(
            model_name='gateway',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
