# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 14:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_RestFul', '0002_auto_20160621_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='cron',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='schType',
        ),
        migrations.AddField(
            model_name='schedule',
            name='ano',
            field=models.IntegerField(blank=True, default=2016, validators=[django.core.validators.MinValueValidator(1976), django.core.validators.MaxValueValidator(2016)]),
        ),
        migrations.AddField(
            model_name='schedule',
            name='dia',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='schedule',
            name='hora',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.AddField(
            model_name='schedule',
            name='mes',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='schedule',
            name='minuto',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
        ),
    ]
