# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_RestFul', '0003_auto_20160810_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='dia',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='hora',
            new_name='hour',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='minuto',
            new_name='minute',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='mes',
            new_name='month',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='ano',
            new_name='year',
        ),
    ]
