# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-21 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_RestFul', '0004_auto_20160810_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='hour',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='minute',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='month',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='year',
            field=models.CharField(max_length=30),
        ),
    ]
