# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-17 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_RestFul', '0005_auto_20160921_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextserver',
            name='accessToken',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
