# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-19 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_RestFul', '0006_contextserver_accesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='persistance',
            name='publisher',
            field=models.BooleanField(default=False),
        ),
    ]
