# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-18 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_RestFul', '0007_persistance_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuator',
            name='uuID',
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='uuID',
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='persistance',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='API_RestFul.Sensor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='uuID',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
