# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-21 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_RestFul', '0008_auto_20161118_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='second',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='hour',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='minute',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='month',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='year',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
