# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-24 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_RestFul', '0009_auto_20161121_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='event',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
