# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-09 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_RestFul', '0012_topicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='topico',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
