# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-09 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_RestFul', '0017_rule_topico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='topico',
        ),
    ]
